# This is a basic workflow to help you get started with Actions

name: CIRunTest

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: Secrets

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      - name: Create SFDX Folder
        run: |
          mkdir ~/sfdx
      - name: Download CLI
        run: |
          wget -qO- https://developer.salesforce.com/media/salesforce-cli/sfdx/channels/stable/sfdx-linux-x64.tar.xz | tar xJ -C ~/sfdx --strip-components 1
      - name: Install CLI
        run: |
          ~/sfdx/install
          export PATH=~/sfdx/bin:$PATH
          # echo "export PATH=~/sfdx/bin:$PATH" >> $BASH_ENV
          sfdx
      - name: Decrypt server key
        run: |
          openssl enc -nosalt -aes-256-cbc -d -in assets/server.key.enc -out assets/server.key -base64 -K ${{Secrets.DECRYPTION_KEY}} -iv ${{Secrets.DECRYPTION_IV}}
      - name: Authorize Org
        run: |
          sfdx force:auth:jwt:grant --clientid ${{Secrets.HUB_CONSUMER_KEY}} --jwtkeyfile assets/server.key --username ${{Secrets.HUB_USER_NAME}} --setdefaultdevhubusername -a HubOrg
      - name: Run Apex Tests
        run: |
          sfdx force:apex:test:run --targetusername HubOrg --wait 10 --resultformat tap --codecoverage --testlevel RunLocalTests
